# Generated by Django 5.1.2 on 2024-10-12 15:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('qualification', models.CharField(blank=True, max_length=200, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('dob', models.DateField()),
                ('blood_group', models.CharField(blank=True, max_length=3, null=True)),
                ('id_no', models.CharField(max_length=50, unique=True)),
                ('aadhar', models.CharField(max_length=12, unique=True)),
                ('pan', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=15)),
                ('emergency_contact', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('insurance_policy_no', models.CharField(blank=True, max_length=50, null=True)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('conveyance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('spl_allowance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff_photos')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(default=django.utils.timezone.now)),
                ('attendance_type', models.CharField(choices=[('Onsite', 'Onsite'), ('Offsite', 'Offsite'), ('WFH', 'Work from Home'), ('Leave', 'Leave')], default='Onsite', max_length=20)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.staff', to_field='id_no')),
            ],
            options={
                'unique_together': {('staff', 'attendance_date')},
            },
        ),
    ]
