# Generated by Django 5.0.3 on 2024-10-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance_type',
            field=models.CharField(choices=[('Onsite', 'Onsite'), ('Offsite', 'Offsite'), ('WFH', 'Work from Home'), ('Leave', 'Leave'), ('Travel', 'Travel')], default='Onsite', max_length=20),
        ),
    ]
